# Generated by Django 4.1.5 on 2023-02-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productgroup_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='girdeji')),
                ('quantity', models.IntegerField(verbose_name='satylan sany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='satylan guni')),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='haryt')),
            ],
            options={
                'verbose_name_plural': 'Arassa Girdejiler',
                'ordering': ('created_at',),
            },
        ),
    ]
