# Generated by Django 4.1.5 on 2023-02-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='prosent')),
                ('homeDiscountedLimit', models.IntegerField(blank=True, null=True, verbose_name='skidka limit')),
                ('homeRecommendLimit', models.IntegerField(blank=True, null=True, verbose_name='maslahat berilyan limit')),
            ],
            options={
                'verbose_name_plural': 'Sazlamalar',
            },
        ),
    ]
