# Generated by Django 4.1.5 on 2023-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='percent',
        ),
        migrations.AddField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='prosent'),
        ),
    ]
