# Generated by Django 4.1.5 on 2023-02-06 04:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Teks')),
                ('videoCover', models.ImageField(blank=True, null=True, upload_to='video_cover/', verbose_name='suraty')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='wideo')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='goşulan güni')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='üýtgedilen güni')),
            ],
            options={
                'verbose_name_plural': 'Postlar',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_img/', verbose_name='surat')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media_app.post', verbose_name='post')),
            ],
            options={
                'verbose_name_plural': 'Suratlar',
            },
        ),
    ]
