# Generated by Django 4.1.5 on 2023-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productgroup_options'),
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='harytlar'),
        ),
    ]
