# Generated by Django 4.1.5 on 2023-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_post_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurhash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='blurhash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash'),
        ),
    ]
