# Generated by Django 4.1.5 on 2023-03-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_post_blurhash_postimage_blurhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videoCover',
            field=models.ImageField(blank=True, null=True, upload_to='video_cover/', verbose_name='Wideo suraty'),
        ),
    ]
