# Generated by Django 4.1.5 on 2023-03-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_alter_post_videocover'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoCover', models.ImageField(blank=True, null=True, upload_to='video_cover/', verbose_name='Wideo suraty')),
                ('blurhash', models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='wideo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media_app.post', verbose_name='post')),
            ],
            options={
                'verbose_name_plural': 'Wideolar',
            },
        ),
    ]
