# Generated by Django 4.1.5 on 2023-03-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_postvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blurhash',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videoCover',
        ),
    ]
