# Generated by Django 4.1.5 on 2023-03-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0006_remove_post_blurhash_remove_post_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
