# Generated by Django 4.1.5 on 2023-03-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productimage_product'),
        ('media_app', '0007_remove_post_active_remove_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.product', verbose_name='harytlar'),
        ),
    ]
