# Generated by Django 4.1.5 on 2023-03-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0008_alter_post_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media_app.post', verbose_name='post'),
        ),
    ]
