# Generated by Django 4.1.5 on 2023-02-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productgroup_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ady')),
                ('phone', models.CharField(max_length=255, verbose_name='telefon belgisi')),
                ('address', models.CharField(max_length=255, verbose_name='öý aglysy')),
                ('orderStatus', models.CharField(choices=[('SARGYT EDILDI', 'SARGYT EDILDI'), ('TASSYKLANDY', 'TASSYKLANDY'), ('GOWŞURYLDY', 'GOWŞURYLDY'), ('BES EDILDI', 'BES EDILDI')], default='SARGYT EDILDI', max_length=255, verbose_name='statusy')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='jemi bahasy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='sargyt edilen wagty')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='üýtgeşme girizilen wagty')),
            ],
            options={
                'verbose_name_plural': 'Sargytlar',
                'ordering': ('orderStatus',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='bahasy')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='sany')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderColors', to='products.color', verbose_name='reňki')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='orders.order', verbose_name='sargyt')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product', verbose_name='haryt')),
            ],
            options={
                'verbose_name_plural': 'Sargyt edilen Harytlar',
            },
        ),
    ]
