# Generated by Django 4.1.5 on 2023-02-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='color',
            new_name='colorId',
        ),
    ]
