# Generated by Django 4.1.5 on 2023-02-05 05:42

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('logo', models.ImageField(upload_to='brand_img/', verbose_name='logo')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='goşulan güni')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='üýtgedilen güni')),
            ],
            options={
                'verbose_name_plural': 'Brandler',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('image', models.ImageField(upload_to='category_img/', verbose_name='suraty')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='orny')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
            ],
            options={
                'verbose_name_plural': 'Ugur',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('hexCode', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='hex kod')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='orny')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
            ],
            options={
                'verbose_name_plural': 'Reňkler',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('description', models.TextField(verbose_name='beýany')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='bahasy')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='arzanladyş baha')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
                ('recommend', models.BooleanField(default=False, verbose_name='maslahat berilyan')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='goşulan güni')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='üýtgedilen güni')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.brand', verbose_name='brand')),
                ('colors', models.ManyToManyField(related_name='colors', to='products.color', verbose_name='reňkleri')),
            ],
            options={
                'verbose_name_plural': 'Harytlar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('image', models.ImageField(upload_to='subcategory_img/', verbose_name='suraty')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='orny')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.category', verbose_name='ugry')),
            ],
            options={
                'verbose_name_plural': 'Bölümler',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='product_img/', verbose_name='surat')),
                ('urlMini', models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='kici surat')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='products.product', verbose_name='haryt')),
            ],
            options={
                'verbose_name_plural': 'Suratlar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.subcategory', verbose_name='bölüm'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('image', models.ImageField(upload_to='banner_img/', verbose_name='suraty')),
                ('discount', models.BooleanField(default=True, verbose_name='arzanladyş')),
                ('recommend', models.BooleanField(default=True, verbose_name='maslahat berýäris')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='orny')),
                ('active', models.BooleanField(default=True, verbose_name='aktiw')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='goşulan güni')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='üýtgedilen güni')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='brand')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='haryt')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory', verbose_name='bölüm')),
            ],
            options={
                'verbose_name_plural': 'Bannerler',
                'ordering': ('index',),
            },
        ),
    ]
