# Generated by Django 4.1.5 on 2023-02-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='baha')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='bellik')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='goşulan güni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productGroup', to='products.product', verbose_name='haryt')),
            ],
            options={
                'verbose_name_plural': 'Harytlaryň Toparlary',
            },
        ),
    ]
