# Generated by Django 4.1.5 on 2023-02-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='sany'),
            preserve_default=False,
        ),
    ]
