# Generated by Django 4.1.5 on 2023-02-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productgroup_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name_plural': 'Harytlaryň Tapgyrlary'},
        ),
    ]
