# Generated by Django 4.1.5 on 2023-02-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name_plural': 'Harydyň Tapgyrlary'},
        ),
    ]
