# Generated by Django 4.1.5 on 2023-02-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='gelen sany'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='galan sany'),
        ),
    ]
