# Generated by Django 4.1.5 on 2023-02-12 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productgroup_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='goşulan güni'),
        ),
    ]
