# Generated by Django 4.1.5 on 2023-02-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_color_hexcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blurhash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash'),
        ),
    ]
