# Generated by Django 4.1.5 on 2023-02-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_blurhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='blurhash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='blurhash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='blurhash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash'),
        ),
    ]
